### ISSUE TITLE
Will you update it?

### ISSUE THREAD

**Issue by FlashJunior** [chuckreynolds/twitch-is-streamer-live#3]
Hi

i saw that u used "kraken". Twitch API v5 is deprecated :-/

https://github.com/chuckreynolds/twitch-is-streamer-live/blob/a1b406b86bc9d584261d013e8783b72fef231448/src/lib.es6.js#L23

Will you update the script to "helix"?

**Comment by chuckreynolds** [comment]
Kraken still works; I still use it all over in bots and stuff.
 
But helix, afaik, would require Oath tokens and more verification. I have not looked into it for this use case, but that is my understanding of helix. So that would require a big rewrite and not likely to upgrade this. TBH I forgot this was even up here.
